--
-- Create table for user and groups
--
CREATE TABLE T_USER (
  ID DECIMAL(18,0),
  SINCE TIMESTAMP,
  NAME VARCHAR(32),
  NICK VARCHAR(32),
  PASSWORD VARCHAR(32),
  PRIMARY KEY (ID)
);

CREATE TABLE T_GROUP (
  ID DECIMAL(18,0),
  SINCE TIMESTAMP,
  NAME VARCHAR(32),
  MANAGER_ID DECIMAL(18,0),
  PRIMARY KEY (ID)
);

CREATE TABLE T_MEMBER_OF (
  ID DECIMAL(18,0),
  USER_ID DECIMAL(18,0),
  GROUP_ID DECIMAL(18,0),
  PRIMARY KEY (ID)
);

ALTER TABLE T_GROUP ADD FOREIGN KEY (MANAGER_ID) REFERENCES T_USER (ID);
ALTER TABLE T_MEMBER_OF ADD FOREIGN KEY (USER_ID) REFERENCES T_USER (ID);
ALTER TABLE T_MEMBER_OF ADD FOREIGN KEY (GROUP_ID) REFERENCES T_GROUP (ID);

CREATE SEQUENCE SEQ_ID_USER START WITH 1000000 INCREMENT BY 10;
CREATE SEQUENCE SEQ_ID_GROUP START WITH 1000000 INCREMENT BY 10;
CREATE SEQUENCE SEQ_ID_MEMBER_OF START WITH 1000000 INCREMENT BY 10;
