--
-- Create table T_NICK_NAME
--
CREATE TABLE T_NICK_NAME (
  ID DECIMAL(18,0),
  TIMESTAMP TIMESTAMP,
  NAME VARCHAR(32),
  NICK VARCHAR(32),
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_ID_NICK_NAME START WITH 1000000 INCREMENT BY 10;
