--
-- Create table for nick names
--
CREATE TABLE T_NICK_NAME (
  ID DECIMAL(18,0),
  SINCE TIMESTAMP,
  NAME VARCHAR(32),
  NICK VARCHAR(32),
  PASSWORD VARCHAR(32),
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_ID_NICK_NAME START WITH 1000000 INCREMENT BY 10;
