--
-- Create table room and subscriber
--
CREATE TABLE T_ROOM (
  ID DECIMAL(18,0),
  OPENING TIMESTAMP,
  CLOSURE TIMESTAMP,
  NAME VARCHAR(32),
  DESCRIPTION VARCHAR(250),
  PUBLIC BOOLEAN,
  MANAGER_ID DECIMAL(18,0),
  PRIMARY KEY (ID)
);

CREATE TABLE T_SUBSCRIBER (
  ID DECIMAL(18,0),
  USER_ID DECIMAL(18,0),
  ROOM_ID DECIMAL(18,0),
  PRIMARY KEY (ID)
);

ALTER TABLE T_ROOM ADD FOREIGN KEY (MANAGER_ID) REFERENCES T_USER (ID);
ALTER TABLE T_SUBSCRIBER ADD FOREIGN KEY (USER_ID) REFERENCES T_USER (ID);
ALTER TABLE T_SUBSCRIBER ADD FOREIGN KEY (ROOM_ID) REFERENCES T_ROOM (ID);

CREATE SEQUENCE SEQ_ID_ROOM START WITH 1000000 INCREMENT BY 10;
CREATE SEQUENCE SEQ_ID_SUBSCRIBER START WITH 1000000 INCREMENT BY 10;
