--
-- Create table message and personal note
--
CREATE TABLE T_MESSAGE (
  ID DECIMAL(18,0),
  TIMESTAMP TIMESTAMP,
  content VARCHAR(2000),
  ROOM_ID DECIMAL(18,0),
  WRITER_ID DECIMAL(18,0),
  PRIMARY KEY (ID)
);

CREATE TABLE T_PERSONAL_NOTE (
  ID DECIMAL(18,0),
  TIMESTAMP TIMESTAMP,
  content VARCHAR(2000),
  RECEIVER_ID DECIMAL(18,0),
  WRITER_ID DECIMAL(18,0),
  PRIMARY KEY (ID)
);

ALTER TABLE T_MESSAGE ADD FOREIGN KEY (WRITER_ID) REFERENCES T_USER (ID);
ALTER TABLE T_PERSONAL_NOTE ADD FOREIGN KEY (RECEIVER_ID) REFERENCES T_USER (ID);
ALTER TABLE T_PERSONAL_NOTE ADD FOREIGN KEY (WRITER_ID) REFERENCES T_USER (ID);

CREATE SEQUENCE SEQ_ID_MESSAGE START WITH 1000000 INCREMENT BY 10;
CREATE SEQUENCE SEQ_ID_PERSONAL_NOTE START WITH 1000000 INCREMENT BY 10;
